docs: 요구사항 분석
bradley4/tdd-racingcar pull request #1
Opened 2022-02-09 00:35 UTC by lbhsos

2022-02-13 12:49 UTC, etff requested changes
바쁜 시간을 내서 과제를 해보셨군요 🙇‍♂️

전체적으로 요구사항을 더 세분화하고 
테스트를 쉽게 할 수 있는 것 할수없는 것을 나눠보면서
테스트 작성연습을 해보면 좋을 것같습니다!

아직 시간이 조금 남았는데요. 
괜찮으시면 과제에서 제시한 요구사항을 구현해보면서 
구현과 테스트를 보완해보면 좋을 것같아요!

2022-02-13 12:49 UTC, etff commented on src/main/java/car/Car.java
> +    int distance = 0;
접근 지시자를 사용하지 않은 이유가 있을까요?

2022-02-13 12:49 UTC, etff commented on src/test/java/car/CarTest.java
> +        assertThat(car.distance).isEqualTo(1);
테스트는 빠르게 독립적으로 실행해서 성공해야합니다. 

`while`은 언젠가 무한하게 실행해서 성공될 수 있지만
될 수도 안될 수도 있는 테스트는 좋은 테스트가 아닙니다!

어떻게 하면 예측이 가능한 테스트를 만들 수 있을까요 🤔

2022-02-13 12:49 UTC, etff commented on src/test/java/car/CarTest.java
> +        assertThat(car.distance).isEqualTo(0);
위의 코멘트와 같습니다!

2022-02-13 12:49 UTC, etff commented on src/test/java/car/CarTest.java
> +    }
테스트를 작성할 때는 쉽게 테스트를 가능한 부분과 가능하지 않은 부분을 
분리해보면 좋습니다. 

테스트하기 쉽지 않은 값을 테스트를 작성하려고 하다보니 테스트를 작성하지 못하게 된 것으로 보입니다!

ex) 쉽지 않은 테스트에는 랜덤한 값이나, DB 데이터, 외부 API 연동케이스 등이 있습니다!

2022-02-13 12:49 UTC, etff commented on src/test/java/car/CarTest.java
> +    private Car car;
취향일 수도 있지만 불필요한 공백인 것같습니다!

2022-02-13 12:49 UTC, etff commented on README.md
> +- [x] 자동차는 random값이 0-3이면 전진하지 않는다.
좀 더 추가적으로 요구사항을 정리해보면 좋을 것같습니다.
실제로 자동차에 이동횟수, 랜덤넘버, 거리 같은 필드가 있는데 이러한 값에
대해 요구사항 정의와 테스트가 안되어있는 것으로 보입니다!

2022-02-13 12:49 UTC, etff commented on src/main/java/car/Car.java
> +        this.randomNumber = getRandomNumber();
현재 필드에서 랜덤수를 유지해야할 이유는 없어 보입니다.
랜덤 숫자가 기준 값을 만족하면 이동하고 아니면 멈추는 정도만 되도 충분할 것같은데 어떻게 생각하시나요?

2022-02-13 12:49 UTC, etff commented on src/main/java/car/Car.java
> +        }
validation이 좋네요!

2022-02-13 12:49 UTC, etff commented on src/main/java/car/Car.java
> +    int distance = 0;
취향일 수도 있는데 생성자를 써보시는 것도 나쁘지 않을 것같아요!

2022-02-13 12:49 UTC, etff commented on src/main/java/car/Car.java
> +    private int getRandomNumber() {
함수의 변경의 이유는 하나가 되어야한다는 단일 책임의 원칙이 있는데요.
메서드명을 보면 랜덤 숫자를 가져온다고 되어있는데
이동횟수도 변경하고 있어요! 혹시 어떻게 생각하시나요?
> [단일책임원칙](https://steady-coding.tistory.com/370)

2022-02-13 12:49 UTC, etff commented on src/main/java/car/Car.java
> +        this.distance += 1;
매직넘버를 제거해보면 어떨까요?
> [매직넘버](https://javabom.tistory.com/28)

2022-02-13 12:54 UTC, lbhsos commented
앗 pr이 열려있는지 모르고 중간 커밋했네요! 
위에 주신 커멘트 반영해서 과제진행하겠습니다~! 감사합니다!

2022-02-13 13:31 UTC, bradley4 commented
로그인을 잘못했네요 😱

2022-02-13 13:39 UTC, bradley4 requested changes
고생하셨습니다. 🙇‍♂️

아직 시간이 남아서 기능을 좀 더 구현해보고, 테스트 작성을 고민해보면 어떨까요?

2022-02-13 13:39 UTC, bradley4 commented on src/main/java/car/Car.java
> +    int distance = 0;
접근지시자를 써보면 어떨까요?

2022-02-13 13:39 UTC, bradley4 commented on src/main/java/car/Car.java
> +    private final int MIN_RANDOM_NUMBER = 0;
상수의 경우 `private static final`로 작성합니다.

2022-02-13 13:39 UTC, bradley4 commented on src/main/java/car/Car.java
> +        this.randomNumber = getRandomNumber();
랜덤 숫자를 자동차가 계속 가지고 있을 필요는 없을 것같아요!

2022-02-13 13:39 UTC, bradley4 commented on src/main/java/car/Car.java
> +    }
랜덤 숫자를 가져오는 기능인데 이동횟수도 증가 시키고 있네요!
메서드에서 단일 책임 원칙을 지켜보면 어떨까요?

2022-02-13 13:39 UTC, bradley4 commented on src/test/java/car/CarTest.java
> +    void increase_moving_count_test() {
race 수행마다에는 테스트에서 반복적으로 기능이 나타날 것으로 예상하는데 반복 기능이 없네요!

2022-02-13 13:39 UTC, bradley4 commented on src/test/java/car/CarTest.java
> +        assertThat(car.distance).isEqualTo(1);
랜덤 값이 3이하여서 이동하지 못하게 되면 테스트는 실패할 것같아요!

2022-02-13 13:39 UTC, bradley4 commented on src/test/java/car/CarTest.java
> +        assertThat(car.distance).isEqualTo(1);
테스트는 독립적으로 빠르게 실행되어야합니다.
정말 운이 없다면 테스트는 성공하지 못하고 무한 대기를 해야할 수도 있습니다.

랜덤한 값을 어떻게 테스트할지 고민해보는 것도 좋을 것같습니다.

2022-02-13 13:39 UTC, bradley4 commented on src/test/java/car/CarTest.java
> +    void random_not_moving_test(){
위와 동일합니다.

2022-02-13 13:39 UTC, bradley4 commented on src/test/java/car/CarTest.java
> +    }
테스트에서는 테스트 하기 쉬운 부분과 어려운 부분을 나누는 것이 중요합니다.
테스트하기 어려운 부분들 db, random, 외부 api 같은 값들은 테스트하기 어려운 부분에 속합니다.

2022-02-13 13:39 UTC, bradley4 commented on README.md
> +- [x] 자동차는 random값이 0-3이면 전진하지 않는다.
자동차 클래스에서는 이동횟수, 랜덤값, 거리같은 필드가 있는데요.
이런 것들도 요구사항에 정의하고 테스트를 작성해보면 어떨까요?

2022-02-17 15:00 UTC, bradley4 approved these changes
고생하셨습니다.🙇‍♂️

2022-02-17 15:00 UTC, merged